// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./enum.js";

export type AppAppearance = {
  id: number;
  theme: Theme;
  codeTheme: Theme;
  thumbnailRandomColor: boolean;
};
