// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelSettings = {
  id: number;
  topicId: number;
  provider: string;
  system: string;
  name: string;
  stream: boolean;
  maxTokens: number;
  temperature: number;
  topK: number;
  topP: number;
};
