// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ProviderType } from "../llm/core";

export type ModelSettings = {
	id: number;
	topicId: number;
	provider: ProviderType;
	system: string;
	modelName: string;
	stream: boolean;
	maxTokens: number;
	temperature?: number;
	topK?: number;
	topP?: number;
};
