/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ["class", '[data-kb-theme="dark"]'],
	content: [
		"src/routes/**/*.{ts,tsx}",
		"src/components/**/*.{ts,tsx}",
		"src/features/**/*.{ts,tsx}",
	],
	prefix: "",
	safelist: [
		"bg-red-200",
		"bg-red-300",
		"bg-red-400",
		"bg-red-500",
		"bg-blue-200",
		"bg-blue-300",
		"bg-blue-400",
		"bg-blue-500",
		"bg-green-200",
		"bg-green-300",
		"bg-green-400",
		"bg-green-500",
		"bg-yellow-200",
		"bg-yellow-300",
		"bg-yellow-400",
		"bg-yellow-500",
		"bg-purple-200",
		"bg-purple-300",
		"bg-purple-400",
		"bg-purple-500",
		"bg-pink-200",
		"bg-pink-300",
		"bg-pink-400",
		"bg-pink-500",
		"bg-indigo-200",
		"bg-indigo-300",
		"bg-indigo-400",
		"bg-indigo-500",
		"bg-red-200/10",
		"bg-red-300/10",
		"bg-red-400/10",
		"bg-red-500/10",
		"bg-blue-200/10",
		"bg-blue-300/10",
		"bg-blue-400/10",
		"bg-blue-500/10",
		"bg-green-200/10",
		"bg-green-300/10",
		"bg-green-400/10",
		"bg-green-500/10",
		"bg-yellow-200/10",
		"bg-yellow-300/10",
		"bg-yellow-400/10",
		"bg-yellow-500/10",
		"bg-purple-200/10",
		"bg-purple-300/10",
		"bg-purple-400/10",
		"bg-purple-500/10",
		"bg-pink-200/10",
		"bg-pink-300/10",
		"bg-pink-400/10",
		"bg-pink-500/10",
		"bg-indigo-200/10",
		"bg-indigo-300/10",
		"bg-indigo-400/10",
		"bg-indigo-500/10",
		"hover:bg-red-200/50",
		"hover:bg-red-300/50",
		"hover:bg-red-400/50",
		"hover:bg-red-500/50",
		"hover:bg-blue-200/50",
		"hover:bg-blue-300/50",
		"hover:bg-blue-400/50",
		"hover:bg-blue-500/50",
		"hover:bg-green-200/50",
		"hover:bg-green-300/50",
		"hover:bg-green-400/50",
		"hover:bg-green-500/50",
		"hover:bg-yellow-200/50",
		"hover:bg-yellow-300/50",
		"hover:bg-yellow-400/50",
		"hover:bg-yellow-500/50",
		"hover:bg-purple-200/50",
		"hover:bg-purple-300/50",
		"hover:bg-purple-400/50",
		"hover:bg-purple-500/50",
		"hover:bg-pink-200/50",
		"hover:bg-pink-300/50",
		"hover:bg-pink-400/50",
		"hover:bg-pink-500/50",
		"hover:bg-indigo-200/50",
		"hover:bg-indigo-300/50",
		"hover:bg-indigo-400/50",
		"hover:bg-indigo-500/50",
	],
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			textColor: {
				foreground: "hsl(var(--foreground))",
			},
			colors: {
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: 0 },
					to: { height: "var(--kb-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--kb-accordion-content-height)" },
					to: { height: 0 },
				},
				"collapsible-down": {
					from: { height: 0 },
					to: { height: "var(--kb-collapsible-content-height)" },
				},
				"collapsible-up": {
					from: { height: "var(--kb-collapsible-content-height)" },
					to: { height: 0 },
				},
				"caret-blink": {
					"0%,70%,100%": { opacity: "1" },
					"20%,50%": { opacity: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
				"collapsible-down": "collapsible-down 0.2s ease-out",
				"collapsible-up": "collapsible-up 0.2s ease-out",
				"caret-blink": "caret-blink 1.25s ease-out infinite",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
