// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicThinkingType } from "../../../../src-tauri/bindings/AnthropicThinkingType.js";

export type AnthropicThinkingConfig = {
  type: AnthropicThinkingType;
  budget_tokens: number;
};
