// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudflareError } from "../src-tauri/bindings/CloudflareError.js";
import type { CloudflareUsage } from "../src-tauri/bindings/CloudflareUsage.js";
import type { Message } from "../src-tauri/bindings/Message.js";

export type ChatInput = { messages: Array<Message>; stream: boolean };

export type CloudflareResponse = {
	errors: Array<CloudflareError>;
	messages: Array<Message>;
	result: CloudflareResult;
	success: boolean;
};

export type CloudflareResult = { response: string; usage: CloudflareUsage };
