// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../src-tauri/src/entity/bindings/serde_json/JsonValue.js";

export type AnthropicModelSettings = {
  id: number;
  topicId: number;
  thinking: JsonValue;
  budgetTokens: number;
  tools: JsonValue | null;
};

export type AppAppearance = {
  id: number;
  theme: Theme;
  codeTheme: Theme;
  thumbnailRandomColor: boolean;
};

export type Message = {
  id: number;
  topicId: number;
  role: Role;
  content: string;
  createdAt: string;
  tokensUsed: number | null;
  updatedAt: string | null;
};

export type ModelSettings = {
  id: number;
  topicId: number;
  provider: string;
  system: string;
  name: string;
  stream: boolean;
  maxTokens: number;
  temperature: number;
  topK: number;
  topP: number;
};

export type ProviderTool = {
  id: number;
  providerName: string;
  tool: JsonValue;
};

export type Role = "system" | "user" | "assistant";

export type Theme = "system" | "dark" | "light";

export type Topic = {
  id: number;
  name: string;
  createdAt: string;
  lastAccessedAt: string;
};
