// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnthropicModelSettings = {
  id: number;
  topicId: number;
  budgetTokens: number;
};

export type ProviderTool = { id: number; providerName: string; toolId: number };

export type Thinking = {
  id: number;
  topicId: number;
  budgetTokens: number;
  enabled: boolean;
};

export type Tool = {
  id: number;
  name: string;
  description: string | null;
  schemaType: string;
};

export type ToolProperty = {
  id: number;
  toolId: number;
  name: string;
  typeName: string;
  description: string | null;
  required: boolean;
};

export type ToolRequiredProp = {
  id: number;
  toolId: number;
  propertyName: string;
};
