// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicSystemPrompt } from "../../../../shared/types/llm/core.js";
import type { AnthropicThinkingConfig } from "./providers/anthropic.js";
import type { AnthropicTool } from "../../../src-tauri/bindings/AnthropicTool.js";
import type { AnthropicToolChoice } from "../../../src-tauri/bindings/AnthropicToolChoice.js";
import type { ContentType } from "../../../src-tauri/bindings/ContentType.js";

export type ChatMessage = { role: ChatRole; content: ContentType };

export type ChatRequest = {
  messages: Array<ChatMessage>;
  system: AnthropicSystemPrompt;
  max_tokens: number | null;
  model?: string;
  stream?: boolean;
  temperature?: number;
  thinking?: AnthropicThinkingConfig;
  top_p?: number;
  top_k?: number;
  seed?: number;
  repetition_penalty?: number;
  frequency_penalty?: number;
  presence_penalty?: number;
  lora?: string;
  tools?: Array<AnthropicTool>;
  tool_choice?: AnthropicToolChoice;
};

export type ChatRole = "system" | "user" | "assistant";

export type ProviderType = "Anthropic" | "Cloudflare" | "Mistral" | "OpenAI";

export type StreamResponse = {
  response: string;
  usage: TokenUsage | null;
  thinking: string | null;
};

export type TokenUsage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};
