// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageMediaType } from "./ImageMediaType.js";
import type { ImageSourceType } from "./ImageSourceType.js";

export type AnthropicImageSource = {
  type: ImageSourceType;
  media_type: ImageMediaType;
  data: string;
};
