// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSchema } from "./InputSchema.js";

export type AnthropicTool = {
  name: string;
  description: string | null;
  input_schema: InputSchema;
};
