// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicThinkingConfig } from "../../shared/types/llm/providers/anthropic.js";
import type { AnthropicTool } from "./AnthropicTool.js";
import type { AnthropicToolChoice } from "./AnthropicToolChoice.js";
import type { BaseModelSettings } from "../../types/core.js";

export type AnthropicModelSettings = {
  base: BaseModelSettings;
  thinking: AnthropicThinkingConfig | null;
  tools: Array<AnthropicTool> | null;
  tool_choice: AnthropicToolChoice | null;
};
