// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicToolChoiceType } from "./AnthropicToolChoiceType.js";

export type AnthropicToolChoice = {
  type: AnthropicToolChoiceType;
  disable_parallel_tool_use: boolean | null;
};
