// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudflareModelProperty } from "./CloudflareModelProperty.js";
import type { CloudflareModelTask } from "./CloudflareModelTask.js";

export type CloudflareModel = {
  id: string;
  source: number;
  name: string;
  description: string;
  task: CloudflareModelTask;
  tags: Array<string>;
  properties: Array<CloudflareModelProperty>;
};
