// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicImageSource } from "./AnthropicImageSource.js";

export type ContentBlock = { "type": "text"; text: string } | {
  "type": "image";
  source: AnthropicImageSource;
};
