// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertySchema } from "./PropertySchema.js";

export type InputSchema = {
  type: string;
  properties: { [key in string]?: PropertySchema };
  required: Array<string> | null;
};
