// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock.js";

export type MessageContent = { "String": string } | {
  "Blocks": Array<ContentBlock>;
};
