// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheControl } from "./CacheControl.js";
import type { SystemPromptType } from "./SystemPromptType.js";

export type SystemPromptData = {
  text: string;
  type: SystemPromptType;
  cache_control: CacheControl | null;
};
